import { Certificate } from '../types';

export const mockCertificates: Certificate[] = [
  {
    id: 'cert-1',
    kodeDokumen: 'CERT-HALAL-001',
    namaSertifikat: 'Sertifikat Halal Produk Olahan Sorgum BPJPH',
    penerbitSertifikat: 'BPJPH Kementerian Agama RI & LPPOM MUI',
    nomorSertifikat: 'ID311100012948120323',
    tanggalTerbit: '12 Maret 2024',
    tanggalKadaluarsa: '12 Maret 2028',
    status: 'AKTIF',
    jenisDokumen: 'Sertifikat Halal',
    fileName: 'Sertifikat_Halal_BPJPH_2024.pdf',
    fileType: 'pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    keterangan: 'Mencakup Tepung Sorgum, Rengginang, dan Gula Cair Sorgum KWT Mitra.',
  },
  {
    id: 'cert-2',
    kodeDokumen: 'CERT-PIRT-002',
    namaSertifikat: 'Izin Edar P-IRT Tepung & Olahan Sorgum',
    penerbitSertifikat: 'Dinas Kesehatan & PTSP Kabupaten Sleman',
    nomorSertifikat: 'P-IRT 2063404010892-28',
    tanggalTerbit: '05 Januari 2023',
    tanggalKadaluarsa: '05 Januari 2028',
    status: 'AKTIF',
    jenisDokumen: 'Izin P-IRT',
    fileName: 'Izin_PIRT_Sleman_2023.png',
    fileType: 'image',
    fileUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80',
    keterangan: 'Kelayakan hygiene saniter tempat produksi dan standar kemasan kedap udara.',
  },
  {
    id: 'cert-3',
    kodeDokumen: 'CERT-LAB-003',
    namaSertifikat: 'Hasil Uji Lab Bebas Gluten (Gluten-Free Test)',
    penerbitSertifikat: 'Laboratorium Penguji Pangan IPB University',
    nomorSertifikat: 'LAB-IPB-2025/11/0491',
    tanggalTerbit: '20 November 2025',
    tanggalKadaluarsa: '20 November 2026',
    status: 'AKTIF',
    jenisDokumen: 'Uji Lab Nutrisi',
    fileName: 'Hasil_Uji_Lab_GlutenFree_IPB.pdf',
    fileType: 'pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    keterangan: 'Terbukti kadar gluten < 5 ppm (Memenuhi standar Internasional Gluten-Free).',
  },
  {
    id: 'cert-4',
    kodeDokumen: 'CERT-ORG-004',
    namaSertifikat: 'Sertifikasi Pertanian Organik Indonesia (SNI 6729:2016)',
    penerbitSertifikat: 'Lembaga Sertifikasi Organik (LSO) Inofice',
    nomorSertifikat: '184-LSO-005-IDN-08-23',
    tanggalTerbit: '14 Agustus 2023',
    tanggalKadaluarsa: '14 Agustus 2026',
    status: 'PROSES',
    jenisDokumen: 'Sertifikat Organik',
    fileName: 'Sertifikat_Organik_SNI_2023.jpg',
    fileType: 'image',
    fileUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80',
    keterangan: 'Sedang dalam pengajuan perpanjangan audit surveillance tahunan ke-3.',
  },
  {
    id: 'cert-5',
    kodeDokumen: 'CERT-LAB-005',
    namaSertifikat: 'Uji Laboratorium Indeks Glikemik Rendah (GI 52)',
    penerbitSertifikat: 'Laboratorium Gizi Universitas Gadjah Mada',
    nomorSertifikat: 'UGM-NUTR-2022-8821',
    tanggalTerbit: '10 Februari 2022',
    tanggalKadaluarsa: '10 Februari 2025',
    status: 'KADALUARSA',
    jenisDokumen: 'Uji Lab Nutrisi',
    fileName: 'Uji_Lab_IG_UGM_2022.pdf',
    fileType: 'pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    keterangan: 'Sertifikat telah lewat masa berlaku, membutuhkan re-sampling uji laboratorium terbaru.',
  },
];
