import { Equipment } from '../types';

export const mockEquipmentList: Equipment[] = [
  {
    id: 'eq-1',
    kodeAlat: 'S-001 Hand Tractor',
    namaPeralatan: 'Hand Tractor Quick G1000 Kubota 8.5 HP',
    kategori: 'Mesin Olah Tanah',
    jumlahStok: 3,
    kondisi: 'Sangat Baik',
    status: 'Tersedia',
    lokasiPenyimpanan: 'Gudang Alat Lahan A (Gubug Tani)',
    tanggalPengadaan: '15 Maret 2024',
    spesifikasi: 'Mesin Diesel Kubota RD 85 DI-1T, Kecepatan 2 Maju 1 Mundur, Kapasitas Kerja 0.12 Ha/Jam.',
    fotoUrl: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=800&q=80',
    terakhirServis: '10 April 2026',
  },
  {
    id: 'eq-2',
    kodeAlat: 'S-002 Thresher',
    namaPeralatan: 'Mesin Perontok Sorgum Multi-Guna Model S-500',
    kategori: 'Pascapanen',
    jumlahStok: 2,
    kondisi: 'Baik',
    status: 'Sedang Digunakan',
    lokasiPenyimpanan: 'Sentra Pengolahan KWT Sorgum',
    tanggalPengadaan: '10 Juni 2024',
    spesifikasi: 'Motor Penggerak Honda GX200 6.5 HP, Kapasitas Perontokan 500-700 kg/jam, Tingkat Kebersihan 98%.',
    fotoUrl: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=800&q=80',
    terakhirServis: '22 Mei 2026',
  },
  {
    id: 'eq-3',
    kodeAlat: 'S-003 Disc Mill',
    namaPeralatan: 'Mesin Penepung Sorgum Disc Mill FFC-23 Stainless',
    kategori: 'Pengolahan Produk',
    jumlahStok: 4,
    kondisi: 'Sangat Baik',
    status: 'Tersedia',
    lokasiPenyimpanan: 'Ruang Produksi Tepung KWT',
    tanggalPengadaan: '02 Januari 2025',
    spesifikasi: 'Bahan Full Stainless Steel 304 (Food Grade), Daya Listrik 3 kW 3-Phase, Kehalusan Tepung 80-100 Mesh.',
    fotoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    terakhirServis: '05 Juni 2026',
  },
  {
    id: 'eq-4',
    kodeAlat: 'S-004 Solar Dryer',
    namaPeralatan: 'Rumah Pengering Efek Rumah Kaca (Solar Dryer Dome)',
    kategori: 'Pengeringan',
    jumlahStok: 1,
    kondisi: 'Baik',
    status: 'Tersedia',
    lokasiPenyimpanan: 'Pelataran Penjemuran Lahan B',
    tanggalPengadaan: '18 Agustus 2024',
    spesifikasi: 'Atap Polycarbonate UV Protection, Dinding Kasa Stainless anti serangga, Luas 6x12 Meter, Kapasitas 2 Ton.',
    fotoUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
    terakhirServis: '12 Januari 2026',
  },
  {
    id: 'eq-5',
    kodeAlat: 'S-005 Extruder',
    namaPeralatan: 'Mesin Extruder Rengginang & Snack Sorgum',
    kategori: 'Pengolahan Produk',
    jumlahStok: 1,
    kondisi: 'Perlu Perbaikan',
    status: 'Dalam Perawatan',
    lokasiPenyimpanan: 'Bengkel Mitratani Jaya',
    tanggalPengadaan: '11 Nopember 2024',
    spesifikasi: 'Kapasitas Pencetakan 80 kg/jam, Temperatur Elemen Pemanas 0-300°C, Otomatis Cutting System.',
    fotoUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
    terakhirServis: '28 Juni 2026',
  },
  {
    id: 'eq-6',
    kodeAlat: 'S-006 Sealer',
    namaPeralatan: 'Continuous Band Sealer FR-900 Stainless with Gas Flushing',
    kategori: 'Pengemasan',
    jumlahStok: 5,
    kondisi: 'Sangat Baik',
    status: 'Tersedia',
    lokasiPenyimpanan: 'Ruang Packaging & Labeling',
    tanggalPengadaan: '20 Februari 2025',
    spesifikasi: 'Kecepatan Penyegelan 0-12m/min, Lebar Sealing 10mm, Cetak Coding Expired Date Emboss.',
    fotoUrl: 'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?auto=format&fit=crop&w=800&q=80',
    terakhirServis: '01 Juli 2026',
  },
];
