import { HarvestRecord } from '../types';

export const mockHarvestRecords: HarvestRecord[] = [
  {
    id: 'hrv-1',
    kodePanen: 'PANEN-2026-001',
    namaLahan: 'Lahan Sektor A (Tani Makmur)',
    varietas: 'Sorgum Bioguma 1',
    tanggalPanen: '14 Mei 2026',
    jumlahHasilKg: 4850,
    kualitasGrade: 'Grade A (Premium)',
    petaniPenanggungJawab: 'Pak Karso & Kelompok Tani Tani Makmur',
    status: 'Selesai',
    catatan: 'Kadar air saat panen 14.2%, warna bulir cokelat kemerahan bersih.',
  },
  {
    id: 'hrv-2',
    kodePanen: 'PANEN-2026-002',
    namaLahan: 'Lahan Sektor B (Sedyo Rukun)',
    varietas: 'Sorgum Numbu',
    tanggalPanen: '18 Mei 2026',
    jumlahHasilKg: 3200,
    kualitasGrade: 'Grade A (Premium)',
    petaniPenanggungJawab: 'Ibu Sugiyanti & KWT Sedyo Rukun',
    status: 'Tersimpan di Gudang',
    catatan: 'Hasil dipisahkan untuk bahan baku utama Tepung Sorgum Pouch 500g.',
  },
  {
    id: 'hrv-3',
    kodePanen: 'PANEN-2026-003',
    namaLahan: 'Lahan Sektor C (Mekar Tani)',
    varietas: 'Sorgum Suri 4 (Manis)',
    tanggalPanen: '02 Juni 2026',
    jumlahHasilKg: 5100,
    kualitasGrade: 'Grade B (Standar)',
    petaniPenanggungJawab: 'Pak Bambang Mulyono',
    status: 'Selesai',
    catatan: 'Batang sorgum manis diproses lebih lanjut menjadi Gula Cair Sorgum Nira.',
  },
  {
    id: 'hrv-4',
    kodePanen: 'PANEN-2026-004',
    namaLahan: 'Lahan Sektor D (Sorgum Lestari)',
    varietas: 'Sorgum Kawali',
    tanggalPanen: '25 Juni 2026',
    jumlahHasilKg: 6400,
    kualitasGrade: 'Grade A (Premium)',
    petaniPenanggungJawab: 'Pak Suwarto & Kelompok Sorgum Lestari',
    status: 'Dalam Proses',
    catatan: 'Prosedur pemisahan bulir di thresher sedang berlangsung di lokasi penjemuran.',
  },
  {
    id: 'hrv-5',
    kodePanen: 'PANEN-2026-005',
    namaLahan: 'Lahan Sektor E (Mulia Tani)',
    varietas: 'Sorgum Bioguma 2',
    tanggalPanen: '10 Juli 2026',
    jumlahHasilKg: 2800,
    kualitasGrade: 'Grade C (Pakan)',
    petaniPenanggungJawab: 'Pak Joko Subagyo',
    status: 'Siap Panen',
    catatan: 'Prediksi panen raya tanggal 12 Juli, siap kirim armada truk pengangkut.',
  },
];
