import { LandPlot } from '../types';

export const mockLandPlots: LandPlot[] = [
  {
    id: 'lhn-1',
    kodeLahan: 'BLK-SKM-01',
    namaLahan: 'Blok A - Sukamaju',
    lokasiDesa: 'Sukamaju',
    kecamatan: 'Cisalak',
    luasHektar: 2.5,
    varietasSorgum: 'Bioguma',
    statusIrigasi: 'Irigasi Teknis',
    jenisTanah: 'Aluvial',
    pemilikKelompokTani: 'KWT Sukamaju Tani',
    statusKesiapan: 'Siap Tanam',
    statusBadge: 'AKTIF',
    panenLaluTon: 12.4,
    fotoUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'lhn-2',
    kodeLahan: 'BLK-CSR-02',
    namaLahan: 'Blok B - Cisarua',
    lokasiDesa: 'Cisarua',
    kecamatan: 'Lembang',
    luasHektar: 1.8,
    varietasSorgum: 'Kawali',
    statusIrigasi: 'Semi Teknis',
    jenisTanah: 'Latosol',
    pemilikKelompokTani: 'Kelompok Tani Cisarua',
    statusKesiapan: 'Masa Pertumbuhan',
    statusBadge: 'PERSIAPAN',
    panenLaluTon: 9.2,
    fotoUrl: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'lhn-3',
    kodeLahan: 'BLK-CAW-03',
    namaLahan: 'Blok C - Ciawi',
    lokasiDesa: 'Ciawi',
    kecamatan: 'Bogor',
    luasHektar: 3.2,
    varietasSorgum: 'Supur-1',
    statusIrigasi: 'Tadah Hujan',
    jenisTanah: 'Grumosol',
    pemilikKelompokTani: 'Gapoktan Ciawi Subur',
    statusKesiapan: 'Siap Tanam',
    statusBadge: 'AKTIF',
    panenLaluTon: 15.1,
    fotoUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'lhn-4',
    kodeLahan: 'BLK-PRG-04',
    namaLahan: 'Blok D - Parung',
    lokasiDesa: 'Parung',
    kecamatan: 'Parung',
    luasHektar: 1.2,
    varietasSorgum: 'Numbu',
    statusIrigasi: 'Irigasi Teknis',
    jenisTanah: 'Aluvial',
    pemilikKelompokTani: 'KWT Parung Mandiri',
    statusKesiapan: 'Masa Pertumbuhan',
    statusBadge: 'PEMBESARAN',
    panenLaluTon: 5.5,
    fotoUrl: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'lhn-5',
    kodeLahan: 'BLK-SBG-05',
    namaLahan: 'Blok E - Subang',
    lokasiDesa: 'Argomulyo',
    kecamatan: 'Cangkringan',
    luasHektar: 4.5,
    varietasSorgum: 'Bioguma 2',
    statusIrigasi: 'Irigasi Teknis',
    jenisTanah: 'Vulkanik Regosol',
    pemilikKelompokTani: 'Kelompok Tani Tani Makmur',
    statusKesiapan: 'Masa Panen',
    statusBadge: 'AKTIF',
    panenLaluTon: 18.3,
    fotoUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'lhn-6',
    kodeLahan: 'BLK-IDM-06',
    namaLahan: 'Blok F - Indramayu',
    lokasiDesa: 'Jatibarang',
    kecamatan: 'Indramayu',
    luasHektar: 5.0,
    varietasSorgum: 'Suri 4',
    statusIrigasi: 'Semi Teknis',
    jenisTanah: 'Alluvial Subur',
    pemilikKelompokTani: 'KWT Indramayu Sorgum',
    statusKesiapan: 'Masa Panen',
    statusBadge: 'AKTIF',
    panenLaluTon: 21.0,
    fotoUrl: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=800&q=80',
  },
];
