import { FinancialExpense } from '../types';

export const mockFinancialExpenses: FinancialExpense[] = [
  {
    id: 'exp-1',
    kodeTransaksi: 'LOG-TRX-001',
    tanggal: '14 Mei 2026',
    kategori: 'Bahan Baku',
    keteranganVendor: 'Beli Pupuk Organik / CV BioTech Agriculture',
    totalBiayaRp: 3500000,
    statusPembayaran: 'LUNAS',
    metodePembayaran: 'Transfer Bank',
    nomorNotaReceipt: 'INV/BIOTECH/2026/05/112',
    catatanNota: 'Pembelian 50 karung pupuk kompos organik terverifikasi SNI.',
    detailItem: [
      { nama: 'Pupuk Kompos Granul Organik 25kg', qty: 40, hargaSatuan: 70000 },
      { nama: 'Pupuk Hayati Cair Bio-Activator 5L', qty: 7, hargaSatuan: 100000 },
    ],
    notaUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'exp-2',
    kodeTransaksi: 'LOG-TRX-002',
    tanggal: '12 Mei 2026',
    kategori: 'Transportasi',
    keteranganVendor: 'Sewa Truk Distribusi Hasil Panen / Jasa Angkut Sleman',
    totalBiayaRp: 1200000,
    statusPembayaran: 'PENDING',
    metodePembayaran: 'Transfer Bank',
    nomorNotaReceipt: 'NOTA-JSA-8812',
    catatanNota: 'Pengangkutan 4.5 ton hasil panen sorgum basah dari Lahan A ke Rumah Pengeringan.',
    detailItem: [
      { nama: 'Jasa Sewa Truk Colt Diesel 6-Roda', qty: 1, hargaSatuan: 1000000 },
      { nama: 'Biaya Bongkar Muat Tenaga Kerja', qty: 4, hargaSatuan: 50000 },
    ],
    notaUrl: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'exp-3',
    kodeTransaksi: 'LOG-TRX-003',
    tanggal: '10 Mei 2026',
    kategori: 'Operasional',
    keteranganVendor: 'Perbaikan Alat Semprot Hama / Bengkel Tani Makmur',
    totalBiayaRp: 450000,
    statusPembayaran: 'LUNAS',
    metodePembayaran: 'Kas Tunai',
    nomorNotaReceipt: 'KW-BKL-0921',
    catatanNota: 'Ganti selang fleksibel & nozzle kuningan sprayer elektrik S-002.',
    detailItem: [
      { nama: 'Nozzle Kuningan Precision High Spray', qty: 2, hargaSatuan: 125000 },
      { nama: 'Selang High Pressure 10 Meter', qty: 1, hargaSatuan: 100000 },
      { nama: 'Ongkos Jasa Servis Mechanic', qty: 1, hargaSatuan: 100000 },
    ],
    notaUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'exp-4',
    kodeTransaksi: 'LOG-TRX-004',
    tanggal: '04 Mei 2026',
    kategori: 'Kemasan',
    keteranganVendor: 'Cetak Pouch & Box Kemasan / PT Kemasan Mulia Jaya',
    totalBiayaRp: 5200000,
    statusPembayaran: 'LUNAS',
    metodePembayaran: 'Transfer Bank',
    nomorNotaReceipt: 'INV-KMJ-2026-041',
    catatanNota: 'Cetak batch ke-3 Standing Pouch Foil 500g & Box Rengginang.',
    detailItem: [
      { nama: 'Standing Pouch Alufoil Ziplock 500g', qty: 2000, hargaSatuan: 1850 },
      { nama: 'Box Duplex Custom Rengginang', qty: 1000, hargaSatuan: 1500 },
    ],
    notaUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'exp-5',
    kodeTransaksi: 'LOG-TRX-005',
    tanggal: '28 April 2026',
    kategori: 'Sertifikasi',
    keteranganVendor: 'Biaya Uji Laboratorium Nutrisi / IPB University Food Lab',
    totalBiayaRp: 2150000,
    statusPembayaran: 'LUNAS',
    metodePembayaran: 'Transfer Bank',
    nomorNotaReceipt: 'RECPT-IPB-LAB-891',
    catatanNota: 'Pengujian profil asam amino, serat pangan, dan Gluten-Free Certificate.',
    detailItem: [
      { nama: 'Paket Uji Laboratorium Bebas Gluten', qty: 1, hargaSatuan: 1250000 },
      { nama: 'Uji Proksimat Pangan Lengkap', qty: 1, hargaSatuan: 900000 },
    ],
    notaUrl: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'exp-6',
    kodeTransaksi: 'LOG-TRX-006',
    tanggal: '20 April 2026',
    kategori: 'Transportasi',
    keteranganVendor: 'Bensin & BBM Operasional Truk / SPBU Pertamina 44.555.02',
    totalBiayaRp: 850000,
    statusPembayaran: 'LUNAS',
    metodePembayaran: 'Kas Tunai',
    nomorNotaReceipt: 'SPBU-ST-882910',
    catatanNota: 'Pengisian Biosolar 125 liter untuk kendaraan angkut hasil panen.',
    detailItem: [
      { nama: 'Solar / Biosolar Industri Ops', qty: 125, hargaSatuan: 6800 },
    ],
    notaUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=600&q=80',
  },
];
