import { PackagingMaterial } from '../types';

export const mockPackagingList: PackagingMaterial[] = [
  {
    id: 'pack-1',
    kodeKemasan: 'KMG-POUCH-500',
    namaKemasan: 'Standing Pouch Alufoil Ziplock Valve 500g',
    kategori: 'Standing Pouch',
    kapasitas: '500 gram',
    stokTersedia: 4200,
    satuan: 'Pcs',
    stokMinimal: 1000,
    pemasok: 'PT Kemasan Mulia Jaya Yogyakarta',
    hargaPerUnitRp: 1850,
    statusStok: 'Stok Cukup',
  },
  {
    id: 'pack-2',
    kodeKemasan: 'KMG-POUCH-250',
    namaKemasan: 'Standing Pouch Window Craft Paper 250g',
    kategori: 'Standing Pouch',
    kapasitas: '250 gram',
    stokTersedia: 650,
    satuan: 'Pcs',
    stokMinimal: 1000,
    pemasok: 'PT Kemasan Mulia Jaya Yogyakarta',
    hargaPerUnitRp: 1400,
    statusStok: 'Stok Menipis',
  },
  {
    id: 'pack-3',
    kodeKemasan: 'KMG-BOX-SAVORY',
    namaKemasan: 'Box Duplex Custom Printing Rengginang 150g',
    kategori: 'Box Custom',
    kapasitas: '150 gram',
    stokTersedia: 2800,
    satuan: 'Pcs',
    stokMinimal: 500,
    pemasok: 'CV Cetak Offset Nusantara',
    hargaPerUnitRp: 2200,
    statusStok: 'Stok Cukup',
  },
  {
    id: 'pack-4',
    kodeKemasan: 'KMG-BOTOL-350',
    namaKemasan: 'Botol Kaca Marasca 350ml Tutup Segel Aluminium',
    kategori: 'Botol Kaca',
    kapasitas: '350 ml',
    stokTersedia: 0,
    satuan: 'Botol',
    stokMinimal: 300,
    pemasok: 'PT Glassindo Industri Indonesia',
    hargaPerUnitRp: 4500,
    statusStok: 'Habis',
  },
  {
    id: 'pack-5',
    kodeKemasan: 'KMG-KARUNG-25',
    namaKemasan: 'Karung Woven PP Food Grade 25kg Laminated',
    kategori: 'Karung Bulk',
    kapasitas: '25 kg',
    stokTersedia: 1150,
    satuan: 'Lembar',
    stokMinimal: 200,
    pemasok: 'UD Plastik Mulia Tani',
    hargaPerUnitRp: 6500,
    statusStok: 'Stok Cukup',
  },
  {
    id: 'pack-6',
    kodeKemasan: 'KMG-STIKER-ECO',
    namaKemasan: 'Stiker Label Vinyl Waterproof Brand Sorgum SCM',
    kategori: 'Aksesoris',
    kapasitas: 'Universal Label',
    stokTersedia: 8500,
    satuan: 'Stiker',
    stokMinimal: 2000,
    pemasok: 'Digital Print Express Sleman',
    hargaPerUnitRp: 350,
    statusStok: 'Stok Cukup',
  },
];
