import { ProductionBatch } from '../types';

export const mockProductionBatches: ProductionBatch[] = [
  {
    id: 'pb-1',
    kodeBatch: 'PRD-2026-001',
    namaProduk: 'Tepung Sorgum Bioguma White Premium 500g',
    kategori: 'Ready to Eat (Siap Konsumsi)',
    tanggalProduksi: '15 Mei 2026',
    tanggalKadaluarsa: '15 Mei 2027',
    jumlahHasil: 2500,
    satuan: 'Kemasan (Pouch)',
    nomorBatchBahanBaku: 'HARVEST-S-014',
    operatorProduksi: 'Ibu KWT Tani Rahayu (Ny. Hastuti)',
    statusQC: 'Lolos QC',
    lokasiGudang: 'Gudang A - Rak Pouch Ready',
  },
  {
    id: 'pb-2',
    kodeBatch: 'PRD-2026-002',
    namaProduk: 'Rengginang Sorgum Bumbu Savory Herbs',
    kategori: 'Ready to Eat (Siap Konsumsi)',
    tanggalProduksi: '18 Mei 2026',
    tanggalKadaluarsa: '18 Nopember 2026',
    jumlahHasil: 1800,
    satuan: 'Box (150g)',
    nomorBatchBahanBaku: 'HARVEST-S-012',
    operatorProduksi: 'Tim Olahan KWT Pertiwi',
    statusQC: 'Lolos QC',
    lokasiGudang: 'Gudang A - Rak Box Snack',
  },
  {
    id: 'pb-3',
    kodeBatch: 'PRD-2026-003',
    namaProduk: 'Gula Cair Sorgum Nira Manis Murni',
    kategori: 'Ready to Eat (Siap Konsumsi)',
    tanggalProduksi: '22 Mei 2026',
    tanggalKadaluarsa: '22 Mei 2028',
    jumlahHasil: 850,
    satuan: 'Botol Kaca (350ml)',
    nomorBatchBahanBaku: 'NIRA-S-008',
    operatorProduksi: 'Pak Slamet & Tim Ekstraksi Nira',
    statusQC: 'Lolos QC',
    lokasiGudang: 'Gudang B - Suhu Ruang Terkontrol',
  },
  {
    id: 'pb-4',
    kodeBatch: 'PRD-2026-004',
    namaProduk: 'Biji Sorgum Sosoh Kering (Grains Raw)',
    kategori: 'Raw (Bahan Mentah)',
    tanggalProduksi: '02 Juni 2026',
    tanggalKadaluarsa: '02 Juni 2027',
    jumlahHasil: 4500,
    satuan: 'Kg (Karung Bulk 25kg)',
    nomorBatchBahanBaku: 'HARVEST-S-018',
    operatorProduksi: 'Unit Sosoh & Cleaner Lahan B',
    statusQC: 'Lolos QC',
    lokasiGudang: 'Gudang Raw Material C',
  },
  {
    id: 'pb-5',
    kodeBatch: 'PRD-2026-005',
    namaProduk: 'Nira Sorgum Murni (Raw Sap Extractions)',
    kategori: 'Raw (Bahan Mentah)',
    tanggalProduksi: '10 Juni 2026',
    tanggalKadaluarsa: '12 Juni 2026',
    jumlahHasil: 1200,
    satuan: 'Liter (Drum Cool Container)',
    nomorBatchBahanBaku: 'NIRA-S-010',
    operatorProduksi: 'Tim Sadap Nira Batang Sorgum',
    statusQC: 'Pending QC',
    lokasiGudang: 'Tangki Pendingin Sementara',
  },
  {
    id: 'pb-6',
    kodeBatch: 'PRD-2026-006',
    namaProduk: 'Tepung Sorgum Halus Mesh 100 Non-Gluten',
    kategori: 'Raw (Bahan Mentah)',
    tanggalProduksi: '20 Juni 2026',
    tanggalKadaluarsa: '20 Juni 2027',
    jumlahHasil: 3200,
    satuan: 'Kg (Bulk Container)',
    nomorBatchBahanBaku: 'HARVEST-S-020',
    operatorProduksi: 'Unit Penepungan Disc Mill S-003',
    statusQC: 'Revisi Batch',
    lokasiGudang: 'Area Isolasi Gudang Raw',
  },
];
